name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniforge (Conda)
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: 'latest'
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          use-mamba: true

      - name: Create conda environment from environment.yml
        run: |
          mamba env create -f environment.yml -n cxxgeom --force
        shell: bash

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          # Use conda-run / mamba-run to execute inside the environment
          mamba run -n cxxgeom cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build
        run: |
          cd build
          mamba run -n cxxgeom ninja -v
        shell: bash

      - name: Run tests
        run: |
          cd build
          mamba run -n cxxgeom ctest --output-on-failure -j 2
        shell: bash

      - name: Upload ctest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ctest-logs-${{ github.run_id }}-${{ matrix.os }}
          path: build/Testing/Temporary
