name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: multiblock
          python-version: 3.10
      - name: Install package
        run: pip install -e .
      - name: Run tests
        run: pytest -v --maxfail=1 --disable-warnings --cov=multiblock
      - name: Lint
        run: |
          black --check multiblock
          flake8 multiblock
          isort --check multiblock
