name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up micromamba (fast conda)
        uses: mamba-org/setup-micromamba@v1
        with:
          version: '1.4.2'
          shell: bash

      - name: Create conda environment from environment.yml (micromamba)
        run: |
          set -euo pipefail
          # micromamba expects a slightly different invocation; try create
          # then fallback to env update
          if micromamba create -f environment.yml -n cxxgeom -y; then
            echo "Environment created"
          else
            echo "Create failed, attempting env update"
            micromamba env update -f environment.yml -n cxxgeom
          fi
        shell: bash

      - name: Clean build directory
        run: |
          # Remove any checked-in or leftover build artifacts (CMakeCache, CMakeFiles)
          # to avoid "CMakeCache.txt directory ... is different" errors when the
          # cache was created on another machine with absolute paths.
          if [ -d build ]; then rm -rf build; fi
        shell: bash

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          # Use micromamba to run cmake inside the environment
          micromamba run -n cxxgeom cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build
        run: |
          cd build
          micromamba run -n cxxgeom ninja -v
        shell: bash

      - name: Run tests
        run: |
          cd build
          micromamba run -n cxxgeom ctest --output-on-failure -j 2
        shell: bash

      - name: Upload ctest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ctest-logs-${{ github.run_id }}-${{ matrix.os }}
          path: build/Testing/Temporary
